### PR TITLE
Update commit hash automatically

### PR DESCRIPTION
**Pull request by j8r**
Follow up of #39

### CODE REVIEW

**Comment by j8r** [comment]
The error is unrelated to the PR change. Even master doesn't build anymore...
Disabling submodules fix this error, but afterwards another one will happen about missing libraries - this was expected.
I can clone the repository recursively locally, outside Flatpak, but inside it seems to have an error.

**Comment by j8r** [comment]
Seems to be due to the `shalow = true` in the `.gitmodules`. Removing it locally did the trick, waiting then for https://github.com/PCSX2/pcsx2/pull/4982 to be merged.

**Comment by marcoluc97** [comment]
@j8r merge done https://github.com/PCSX2/pcsx2/pull/4982

**Comment by j8r** [comment]
It works :heart: 
Ready for review @TingPing.

**Pull request merged**
