### PR TITLE
update git version

### PR DESCRIPTION
**Pull request by Mikaela**
I took example from https://github.com/flathub/net.pcsx2.PCSX2/commit/1ba2d512bc357e59aff98282b569557a44035e93#diff-684134c60da3afa276d9955e3480dd0d and checked the latest commit on that repository.

### CODE REVIEW

**Comment by Mikaela** [comment]
GitHub didn't work like I expected it to work. I wanted to point some lines and ask if they should be changed too?

* https://github.com/flathub/net.pcsx2.PCSX2/blob/133e8f3186858b9bb74d17b2461011e3efe918b1/net.pcsx2.PCSX2.appdata.xml#L27
* https://github.com/flathub/net.pcsx2.PCSX2/blob/133e8f3186858b9bb74d17b2461011e3efe918b1/net.pcsx2.PCSX2.json#L51-L52
* https://github.com/flathub/net.pcsx2.PCSX2/blob/133e8f3186858b9bb74d17b2461011e3efe918b1/net.pcsx2.PCSX2.json#L67-L68
* https://github.com/flathub/net.pcsx2.PCSX2/blob/133e8f3186858b9bb74d17b2461011e3efe918b1/net.pcsx2.PCSX2.json#L88-L89
* https://github.com/flathub/net.pcsx2.PCSX2/blob/133e8f3186858b9bb74d17b2461011e3efe918b1/net.pcsx2.PCSX2.json#L101-L102
* https://github.com/flathub/net.pcsx2.PCSX2/blob/133e8f3186858b9bb74d17b2461011e3efe918b1/net.pcsx2.PCSX2.json#L125-L126

**Comment by Mikaela** [comment]
I don't understand the error, is it an answer to my question on those other lines or does PCSX2 think that the build environment is too old or something?

**Comment by TingPing** [comment]
Update the `shared-modules` submodule.

**Comment by TingPing** [comment]
You can update the date in the appdata too.

**Comment by Mikaela** [comment]
> Update the shared-modules submodule.
> You can update the date in the appdata too.

Thanks :)

> `flatpak install --user https://dl.flathub.org/build-repo/2991/net.pcsx2.PCSX2.flatpakref`

`error: No such ref 'app/net.pcsx2.PCSX2/x86_64/test' in remote pcsx2-origin`

**Pull request merged**
