### PR TITLE
Update to PCSX2 1.7 x64

### PR DESCRIPTION
**Pull request by Blackburn29**
- Updates to latest git build of PCSX2 1.7 (x64)
- Updates runtime to 20.08
- Adds support for libpcap
- Removes all i386-compat references and dependencies
- Adds readme for building/DEV9 networking notes

### CODE REVIEW

**Comment by HugLifeTiZ** [comment]
bot, build

**Comment by HugLifeTiZ** [comment]
I tested this and it seems to work fine. What's stopping this from getting merged? I would imagine it's something WRT to stable releases vs. development releases, right? This package hasn't been touched for over a year, so I imagine we need to do the same thing we're doing with Dolphin and release in time with progress reports.

**Comment by Blackburn29** [comment]
@HugLifeTiZ  I honestly don't know. It seems like this flatpak has mostly been abandoned, however I still use it.

**Comment by TingPing** [comment]
It wasn't touched because PCSX2's last tagged release is 7 years old. Its not exactly an evolving project.

I missed this PR and missed the fact upstream added x64 support.

**Pull request merged**
