### PR TITLE
Add pcsx2_patches

### LINKED ISSUE #220: Include official widescreen and no-interlacing patches from upstream distribution
I've found that the Flatpak doesn't come with any widescreen and no-interlacing patches, which makes the options to load those patcheds ineffective in PCSX2's options menu until you install them yourself from https://github.com/PCSX2/pcsx2_patches.

Could this be added in the Flatpak build to match official builds? Thanks in advance :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by CharlesThobe**
Closes #220

### CODE REVIEW

**Comment by j8r** [comment]
@Calinou do you confirm it works for you?

**Review by Calinou — APPROVED** [review]
Tested locally (after removing my self-installed folders), it works :slightly_smiling_face:

**Comment by j8r** [comment]
Nice, thanks @CharlesThobe !

**Comment by CharlesThobe** [comment]
You're welcome :frog:

**Pull request merged**
