### PR TITLE
Add "automerge-flathubbot-prs"

### PR DESCRIPTION
**Pull request by j8r**
Prevents to be spammed by PRs now that PCSX2 tags for nearly every commit pushed.

cc @TingPing . Sorry to  "ping" you because you won't get notified otherwise, due to not watching the repo.

Of course other PRs opened by the @flathubbot can be closed afterwards.

### CODE REVIEW

**Comment by TingPing** [comment]
Uh, i don't like that, maybe it should be removed uf they tag that often.

**Comment by j8r** [comment]
Or, we can just auto update PCSX2 itself? I've made GitHub Actions to do that on other projects, but they are considered in beta so the latest commit the better.
If the build fail, it won't be uploaded anyway.

**Comment by TingPing** [comment]
An application being deployed multiple times per day is very much not what we want. It just wastes everybodys limited resources.

A more reasonable cadence to me is like monthly updates.

**Comment by j8r** [comment]
Monthly seems long. On other projects, I've done daily but can be done weekly, I'll be ok.

**Comment by TingPing** [comment]
I'd accept weekly. Flathub infrastructure is mostly from donations and has limits, I don't want want to use it for trivial updates.

**Comment by j8r** [comment]
Sure. I also think they are doing this only for pre-releases, at least they are tagged as such.

**Pull request closed without merging**
